name: to_do
description: A todo flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  auto_route: null
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.7.1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: null
  flutter_native_timezone: ^2.0.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  mobx: ^2.0.7+5
  provider: ^6.0.3
  rxdart: ^0.27.5
  date_picker_timeline:
  flutter_mobx_form_validation_kit:

dev_dependencies:
  auto_route_generator: null
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
